In [1]:
# a function to compute 5/0 and use try/except to catch the exceptions.

def try_except():
    try:
        result = 5 / 0
        return result
    except:
        print("number can not be divided by zero(0)")
        
def main():
    
    res = try_except()
    
if __name__=='__main__':main()
    

number can not be divided by zero(0)


In [2]:
#Implement a Python program to generate all sentences where subject is in ["Americans",
#"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

def main():
    subjects=["Americans","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]
    for i in subjects:
        for j in verbs:
            for k in objects:
                str1 =i+" "+j+" "+k
                print(str1)
                
if __name__=='__main__':main()


Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [3]:
import numpy as np

#Write a function so that the columns of the output matrix are powers of the input vector.
#The order of the powers is determined by the increasing boolean argument. Specifically, when
#increasing is False, the i-th output column is the input vector raised element-wise to the power
#of N - i - 1.
l=[3,5,4]
n=len(l)
a=np.array(l)
def van(a,increasing=False):
    b=[]
    if increasing == False:
        for i in range(0,len(a)):
            for j in range(0,len(a)):
                temp=a[i]**(n-j-1)
                b.append(temp)
    else:
        for i in range(0,len(a)):
            for j in range(len(a)-1,-1,-1):
                temp=a[i]**(n-j-1)
                b.append(temp)
        
    arr=np.array(b)
    arr=arr.reshape(n,n)
    return arr
result=van(a)
res = van(a,True)
print("when increasing is False \n")
print(result)
print("when increasing is true \n")
print(res)
    

when increasing is False 

[[ 9  3  1]
 [25  5  1]
 [16  4  1]]
when increasing is true 

[[ 1  3  9]
 [ 1  5 25]
 [ 1  4 16]]
